project:
  type: website
  output-dir: docs

website:
  title: "Ajith Raju Aumbati"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
    

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofint: courier view
    css: styles.css




