project:
  type: website
  output-dir: docs

website:
  title: "Ajith Raju"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Mid-project.qmd
      - Code-final.qmd
      
    

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofint: courier view
    css: styles.css




